spring.datasource.url=${url_database}
spring.datasource.username=${user_database}
spring.datasource.password=${password_database}
spring.jpa.hibernate.ddl-auto=create-drop

aw.storage.s3.key-id=${key_id}
aw.storage.s3.key-secret=${key_secret}
aw.storage.s3.bucket=icpa-ecommerce-bucket
aw.storage.s3.region=us-east-1
aw.storage.s3.endpoint=http://127.0.0.1:9000


server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=xxxxxxxxxxxxxx
spring.mail.password=xxxxxxxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

